### ISSUE TITLE
Transparent background

### ISSUE THREAD

**Issue by i-TechSoftware** [AvaloniaUI/Avalonia.GIF#25]
Hi!
Does Avalonia.GIF support transparent background?
I have a turquoise background instead of a transparent background.
![Screenshot_16](https://github.com/AvaloniaUI/Avalonia.GIF/assets/48829872/6a3bb53d-7253-4e2a-9c81-dcffb3425c39)

UPD: At the same time, a transparent background is displayed in the designer.

**Comment by jmacato** [comment]
It should, i just removed the code that draws that. you're using the new PR i have right?

**Comment by i-TechSoftware** [comment]
Yes, that's right, I'm using rc1

**Comment by i-TechSoftware** [comment]
@jmacato Thanks, I saw the fix, now everything works as it should :)
