### ISSUE TITLE
Source binding issue

### ISSUE THREAD

**Issue by pyking-wang** [AvaloniaUI/Avalonia.GIF#26]
![image](https://github.com/AvaloniaUI/Avalonia.GIF/assets/76192669/f73a3f42-b1fe-4663-acdf-5b42deada916)
There is no problem with the demo running, why am I changing to directly bind resources and cannot use them.
Where did I go wrong?

**Comment by jmacato** [comment]
```
```

**Comment by jmacato** [comment]
Fixed by https://github.com/AvaloniaUI/Avalonia.GIF/pull/27
