### ISSUE TITLE
Loading a GIF via a File or URL stream results in InvalidGifStreamException

### ISSUE THREAD

**Issue by kevinta893** [AvaloniaUI/Avalonia.GIF#3]
Hi,

So I'm trying to load GIF images over URL and File streams and I keep getting InvalidGifStreamException("Not a GIF stream."); exceptions.

Sample code:

```
var imgStream = File.OpenRead(imageName);
_gifImage.SourceStream = imgStream;
```

Test GIF
https://github.com/AvaloniaUI/Avalonia.GIF/blob/master/AvaloniaGif.Demo/Images/c-loader.gif

Been Compiling with .NET Core 3.1

Will GIF streams from these sources (and potentially more) be supported?

**Comment by jmacato** [comment]
You might need to reset the position of the stream when you pass it to GifImage. I'd reckon it'd be at the end of the stream when it's passed from File.OpenRead.

**Comment by jmacato** [comment]
i fixed it here https://github.com/AvaloniaUI/Avalonia.GIF/blob/90cc9a35e622a2d8e2ded0e0b2abc5f014377aab/AvaloniaGif/GifInstance.cs#L48 feel free to comment if it's fixed on your side.
