### ISSUE TITLE
Some GIF images display problem

### ISSUE THREAD

**Issue by rmbadmin** [AvaloniaUI/Avalonia.GIF#9]
![1](https://media.st.dl.eccdnx.com/steamcommunity/public/images/items/1203420/d466feaada5718256f592b789651b13fec009a90.gif)

![2](https://media.st.dl.eccdnx.com/steamcommunity/public/images/items/1203420/866256673c521a3935be83765326ae43327b4cb5.gif)

There is a problem with displaying the above two GIF avatars 

I'm not sure what the problem is .

**Comment by jmacato** [comment]
Please ping if this is still an issue, closing for now

**Comment by rmbadmin** [comment]
![3](https://github.com/AvaloniaUI/Avalonia.GIF/assets/12234359/cabe51ec-8462-4afc-9501-ec4f7e5459ea)

I'm pretty sure the problem still exists

**Comment by neelabo** [comment]
It seems to me that this phenomenon probably occurs in GIFs with the "Interlaced Flag" turned on.

**Comment by jmacato** [comment]
this is fixed at master (included the GIF in this issue as well on the latest demo).

**Comment by jmacato** [comment]
this is fixed at master (included the GIF in this issue as well on the latest demo).
